######################################################################
# Automatically generated by qmake (2.01a) Sat Nov 1 11:34:57 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Board.h MainWindow.h
SOURCES += Board.cpp main.cpp MainWindow.cpp
